name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Turn on debug mode if needed
        run: |
          export DEBUG=${DEBUG:-false}
          if [[ "$DEBUG" == "true" ]]; then
            env
          fi
        env:
          DEBUG: ${{secrets.DEBUG}}

      - name: Install goose
        run: |
          go get -u github.com/pressly/goose/cmd/goose

      - name: Migrate database
        run: |
          cd backend/migrations
          $(go env GOPATH)/bin/goose postgres $PG up
        env:
          PG: postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/test?sslmode=disable

      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.1

      - name: Run tests and extract coverage
        run: |
          cd backend/app
          go test -mod=vendor -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/backend/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/backend/profile.cov_tmp | grep -v "mock_" > $GITHUB_WORKSPACE/backend/profile.cov
        env:
          CGO_ENABLED: 0
          DB_TEST: postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/test?sslmode=disable

      - name: Install golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.24.0

      - name: Run linters
        run: $GITHUB_WORKSPACE/golangci-lint run --config .golangci.yml ./...
        working-directory: backend
        env:
          GOFLAGS: "-mod=mod"
          CGO_ENABLED: 0

      - name: Submit coverage to codecov
        run: |
          cat $GITHUB_WORKSPACE/backend/profile.cov > $GITHUB_WORKSPACE/backend/coverage.txt
          cd $GITHUB_WORKSPACE/backend
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GOFLAGS: "-mod=mod"
          CGO_ENABLED: 0